//go:build ignore

// Command fontawesome_gen writes the two files the renderer derives from a
// Font Awesome Free download: css/fontawesome.css, the class for every free
// solid icon, and icons.txt, the names a Nav may use.
//
//	go run fontawesome_gen.go <fontawesome-free-X-desktop>
//
// The font, fonts/fa-solid-900.otf, is copied from that download by hand, with
// its license.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

type icon struct {
	Unicode string   `json:"unicode"`
	Free    []string `json:"free"`
	Aliases struct {
		Names []string `json:"names"`
	} `json:"aliases"`
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: go run fontawesome_gen.go <fontawesome-free-desktop-dir>")
		os.Exit(2)
	}
	raw, err := os.ReadFile(filepath.Join(os.Args[1], "metadata", "icons.json"))
	check(err)
	var all map[string]icon
	check(json.Unmarshal(raw, &all))

	codes := map[string]string{} // class name -> code point, aliases included
	for name, ic := range all {
		if !slices.Contains(ic.Free, "solid") {
			continue
		}
		codes[name] = ic.Unicode
		for _, alias := range ic.Aliases.Names {
			codes[alias] = ic.Unicode
		}
	}
	names := make([]string, 0, len(codes))
	for name := range codes {
		names = append(names, name)
	}
	slices.Sort(names)

	var css strings.Builder
	css.WriteString(`/* Font Awesome Free, solid style: the class for each icon, generated by
   fontawesome_gen.go from the Font Awesome Free download. The font is SIL OFL 1.1,
   see fonts/LICENSE-fontawesome.txt. An icon is <i class="fa-solid fa-house">. */
@font-face {
  font-family: 'Font Awesome Solid';
  font-style: normal;
  font-weight: 900;
  font-display: block;
  src: url(fa-solid-900.otf) format('opentype');
}
.fa-solid {
  font-family: 'Font Awesome Solid';
  font-style: normal;
  font-weight: 900;
  line-height: 1;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  text-rendering: auto;
  -webkit-font-smoothing: antialiased;
}
`)
	for _, name := range names {
		fmt.Fprintf(&css, ".fa-%s::before{content:\"\\%s\"}\n", name, codes[name])
	}
	check(os.WriteFile("css/fontawesome.css", []byte(css.String()), 0o644))
	check(os.WriteFile("icons.txt", []byte("\n"+strings.Join(names, "\n")+"\n"), 0o644))
	fmt.Println(len(names), "icons")
}

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}
